#!/usr/bin/bash

fruits=('apple' 'banana' 'orange')

echo ${fruits[@]} # display all elements in the array
echo ${fruits[0]} # element of 0
echo ${fruits[1]} # element of 1
echo ${fruits[-1]} # last element
