#!/usr/bin/bash
echo "Total arguments: $#"
echo "1st argument: $1"
echo "2nd argument: $2"
echo "3rd argument: $3"
echo "4th argument: $4"
echo "5th argument: $5"
echo "6th argument: $6"
echo "7th argument: $7"
echo "8th argument: $8"
echo "9th argument: $9"
echo "10 argument: ${10}"